### ISSUE TITLE
talk_matterbridge downloads/installs Linux version on FreeBSD

### ISSUE THREAD

**Issue by LunkSnee** [nextcloud/talk_matterbridge#27]
The installer downloads the wrong version. Instead, please look at the platform and have it install the FreeBSD version if that is the platform nextcloud is running on.

**Comment by gary-kim** [comment]
This app doesn't support operating systems other than Linux since that is the only OS Nextcloud officially supports. If you're using FreeBSD, I'd recommend taking a look at installing [Matterbridge](https://github.com/42wim/matterbridge) manually and [setting Nextcloud Talk to use it](https://nextcloud-talk.readthedocs.io/en/latest/matterbridge/#use-a-custom-matterbridge-binary).
