### ISSUE TITLE
Discord bridge only works with channel name, not channel ID

### ISSUE THREAD

**Issue by helge17** [nextcloud/talk_matterbridge#71]
When setting up a Discord bridge and entering the channel ID in the settings dialog I get the following error in bridge-XYZ.log as soon als I type a message:

`msg="SendMessage failed: Could not find channelID for 1001234567812345678"`
(after adding -debug to $matterbridgeCmd in spreed/lib/MatterbridgeManager.php)

When entering the channel name the chat works just fine.

**Comment by D1sturbed666** [comment]
Issue still exists, thankfully I stumbled onto this open issue and got it working with channel name. However, it would be nice to get this fixed as Discord generally uses IDs to make things easier now days...

**Comment by Fibbicles** [comment]
How does this issue still exist 4 years later? I literally have spent 3 days trying to figure out why Discord was not working until I found this, IDs makes more sense also because most servers utilize some kind of unicode emoji or symbols within their channel names. I might see if I could make a fork to use to IDs and pull request it.

**Comment by nickvergessen** [comment]
I'm closing this here, as this repo just ships the binary.
We can try to improve the UI in the spreed repo with https://github.com/nextcloud/spreed/issues/13877 to add a hint about `ID:…`
